### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by kumarpratyush4** [signalfx/signalfx-php-tracing#15]
How do I install the smart agent for php?

**Comment by rmfitzpatrick** [comment]
@kumarpratyush4 the [Smart Agent](https://github.com/signalfx/signalfx-agent) is a standalone runnable for SFx users that can be deployed in [a number of ways](https://docs.signalfx.com/en/latest/apm2/apm2-getting-started/apm2-smart-agent.html), and isn't used by php directly.  The tracing library for php reports Zipkin v2 JSON-encoded spans so is also compatible with any collector that supports that format as well.

**Comment by kumarpratyush4** [comment]
so these are the steps I followed
1. installed the signal-fx-tracer
2. started zipkin endpoint on localhost:9411
3. routed the 9080 port HTTP request to port 9411 using iptables
But still I am not able to see the traces on zipkin backend. Any steps I am missing here?

**Comment by rmfitzpatrick** [comment]
Have you tried setting the `SIGNALFX_ENDPOINT_URL` to something like `http://localhost:9411/api/v2/spans`?
