### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by hwhite-bamboohealth** [signalfx/signalfx-php-tracing#68]
It appears that PHP 8.1 is not supported with the last release that was created. Can someone please provide a new release that provides support for PHP 8.1?

**Comment by hwhite-bamboohealth** [comment]
To provide more context. This is the error we are receiving upon installation:

16:38:22  + strip --strip-all modules/opcache.so
16:38:22  make: Circular jit/zend_jit.lo <- jit/zend_jit.lo dependency dropped.
16:38:22  Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20210902/
16:38:22  /usr/local/bin/docker-php-ext-enable: 5: cd: can't cd to [24-Aug-2022 20:38:19 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/signalfx-php-tracing/extensions/signalfx_tracing-20210902.so' (tried: /opt/signalfx-php-tracing/extensions/signalfx_tracing-20210902.so (/opt/signalfx-php-tracing/extensions/signalfx_tracing-20210902.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902//opt/signalfx-php-tracing/extensions/signalfx_tracing-20210902.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20210902//opt/signalfx-php-tracing/extensions/signalfx_tracing-20210902.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
16:38:22  /usr/local/lib/php/extensions/no-debug-non-zts-20210902

**Comment by seemk** [comment]
PHP 8.1 is now supported as of the latest [release](https://github.com/signalfx/signalfx-php-tracing/releases/tag/0.78.0-beta-sfx7)
