### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by ccoqueiro** [signalfx/signalfx-php-tracing#71]
We note that many companies have adopted arm64 architecture (cheaper than using AMD64 architecture on AWS), so we have the version of otel collector that already supports this architecture. In this sense, it would be interesting to have a version of the PHP library ARM64 version.

**Comment by seemk** [comment]
The latest [release](https://github.com/signalfx/signalfx-php-tracing/releases/tag/0.78.0-beta-sfx7) has ARM support now
